#!/bin/bash

function file_ends_with_newline() {
    [[ $(tail -c1 "$1" | wc -l) -gt 0 ]]
}

echo "Chapter Number"

read chapter

echo "Title"

read title

STR="chapter-"$chapter
PRETTY="Chapter "$chapter" -"

for one_thing in $title; do
    STR+="-"
    PRETTY+=" "
    PRETTY_WORD="$(tr '[:lower:]' '[:upper:]' <<< ${one_thing:0:1})${one_thing:1}"
    STR+=$one_thing
    PRETTY+=$PRETTY_WORD
done

touch $STR.md
echo "# "$PRETTY >> $STR.md
echo "" >> $STR.md
echo "{Type the chapter summary here}" >> $STR.md
echo "" >> $STR.md
echo "[Back to index.](./index.md)" >> $STR.md

if ! file_ends_with_newline index.md
then
    echo "" >> index.md
fi

echo "* ["$PRETTY"](./"$STR".md)" >> index.md
