
\title{1-proofs}
\author{leweymetcalf }
\date{July 2020}
\maketitle


\section{Quantifiers}\label{sec:quantifiers}

\subsection{$\forall$ is to say 'for all'}\label{subsec:nullis-to-say-'for-all'}

"for every $y$ in set $D$, $p(y)$ is True" can be said as:

\[\forall y \in D. p(y)\]

\subsection{$\exists$ is to say 'there exists'}\label{subsec:nullis-to-say-'there-exists'}

"There exists $x$ in set $D$ where $p(x)$ is True" can be said as:

\[\exists x \in D. p(x)\]


\section{Implications}\label{sec:implications}

$P$ can be said to imply $Q$:

\[P \rightarrow Q\].

This could also be phrased as "If $P$ then $Q$.
\newline
The contrapositive to this statement is:

\[ \overline{P} \rightarrow \overline{P} \]